# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main iterative updates for BiSSLB model using RcppArmadillo.
#'
#' This function performs the core iterative updates for the Binary Spike-and-Slab
#' Lasso Biclustering (BiSSLB) model. It alternates between updating the latent
#' row profile matrix \eqn{A}, column profile matrix \eqn{B}, and sparsity parameters
#' (\eqn{\theta}, \eqn{\tilde{\theta}}) under spike-and-slab priors. It supports
#' optional Indian Buffet Process (IBP) reordering and soft-thresholding.
#'
#' @param mu A numeric vector representing the baseline signal (location parameter).
#' @param A A numeric matrix representing initial row profiles.
#' @param B A numeric matrix representing initial column profiles.
#' @param tilde_thetas A numeric vector of initial sparsity parameters for \eqn{A}.
#' @param thetas A numeric vector of initial sparsity parameters for \eqn{B}.
#' @param Y A binary observation matrix to be approximated.
#' @param xi A positive scalar controlling the pseudo-likelihood scale.
#' @param eta A small positive scalar controlling soft-thresholding aggressiveness.
#' @param tilde_lambdas Spike-and-slab prior lambdas for \eqn{A}.
#' @param lambdas Spike-and-slab prior lambdas for \eqn{B}.
#' @param tilde_alpha Shape parameter of Beta prior on \eqn{\tilde{\theta}} (for A).
#' @param tilde_beta Rate parameter of Beta prior on \eqn{\tilde{\theta}} (for A).
#' @param alpha Shape parameter of Beta prior on \eqn{\theta} (for B).
#' @param beta Rate parameter of Beta prior on \eqn{\theta} (for B).
#' @param tol Convergence tolerance for relative change in log-likelihood.
#' @param max_iter Maximum number of EM-like iterations.
#' @param IBP Integer flag (1 = enable, 0 = disable) for IBP-style column reordering.
#' @param I Number of rows in \eqn{A} (features).
#' @param J Number of rows in \eqn{B} (samples).
#'
#' @return A list containing:
#' \describe{
#'   \item{A}{Final row profile matrix \eqn{A}.}
#'   \item{B}{Final column profile matrix \eqn{B}.}
#'   \item{mu}{Updated location parameter vector.}
#'   \item{tilde_thetas}{Updated sparsity vector for \eqn{A}.}
#'   \item{thetas}{Updated sparsity vector for \eqn{B}.}
#'   \item{delta_logLikelihood_save}{Vector of log-likelihood changes per iteration.}
#'   \item{logLikelihood_save}{Vector of log-likelihood values per iteration.}
#'   \item{BIC}{Final Bayesian Information Criterion (BIC) value.}
#' }
#'
#' @keywords internal
#'
main_iterations <- function(mu, A, B, tilde_thetas, thetas, Y, xi, eta, tilde_lambdas, lambdas, tilde_alpha, tilde_beta, alpha, beta, tol, max_iter, IBP, I, J) {
    .Call(`_BiSSLB_main_iterations`, mu, A, B, tilde_thetas, thetas, Y, xi, eta, tilde_lambdas, lambdas, tilde_alpha, tilde_beta, alpha, beta, tol, max_iter, IBP, I, J)
}

